//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMatriculaCibertec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retiro
    {
        public int IdRetiro { get; set; }
        public int IdMatricula { get; set; }
        public System.DateTime FechaRetiro { get; set; }
        public string Motivo { get; set; }
    
        public virtual Matricula Matricula { get; set; }
    }
}
